### ISSUE TITLE
Selectable main query text

### ISSUE THREAD

**Issue by joeiannone** [ErikEJ/SqlQueryStress#129] opened 2022-05-16 16:08 UTC
Hey - Not sure if anyone else would be into this use case but I was thinking it would be cool to have the option to select/highlight text in the main query editor, and on clicking the go button only execute the highlighted query. Similarly to SSMS behavior. So that way you could test multiple queries in a single window and quickly see the different results. I think I have a good solution. Would you be interested in a PR for that functionality?

Thanks

Joe

**Comment by ErikEJ** [comment] 2022-05-17 05:31
Sounds relevant. Possible duplicate of #6

**Comment by ErikEJ** [comment] 2022-05-17 19:09
Thanks for your contribution

**Closed** 2022-05-17 19:09 UTC
